INSERT INTO pests VALUES(1, 'Arthropoda', 'Argentine Ant', 'Insect');
INSERT INTO pests VALUES(2, 'Arthropoda', 'Fire Ant', 'Insect');
INSERT INTO pests VALUES(3, 'Arthropoda', 'Earwig', 'Insect');
INSERT INTO pests VALUES(4, 'Chordata', 'Brown Rat', 'Mammal');
INSERT INTO pests VALUES(5, 'Arthropoda', 'German Cockroach', 'Insect');
INSERT INTO pests VALUES(6, 'Arthropoda', 'American Cockroach', 'Insect');
INSERT INTO pests VALUES(7, 'Chordata', 'Gray Mouse', 'Mammal');
INSERT INTO pests VALUES(8, 'Insecta', 'Bed Bug', 'Insect');
INSERT INTO pests VALUES(9, 'Arthropoda', 'Pharaoh Ant', 'Insect');
INSERT INTO pests VALUES(10, 'Arthropoda', 'Indian Meal Moth', 'Insect');