\i ins_customers.sql;
\i ins_chemicals.sql;
\i ins_properties.sql;
\i ins_pests.sql;
\i ins_technicians.sql;
\i ins_routes.sql;
\i ins_routes_properties.sql;
\i ins_contracts.sql;
\i ins_pests_effective_chemicals.sql;