INSERT INTO properties VALUES (1, 'RESIDENTIAL', '12309 Quiet Pasture Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (2, 'RESIDENTIAL', '12562 High Country Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (3, 'RESIDENTIAL', '11004 Snowcreek Falls Ave.', 'Bakersfield', 'CA', '93312', 'Monthly');
INSERT INTO properties VALUES (4, 'RESIDENTIAL', '13511 Scafell Pike St.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (5, 'RESIDENTIAL', '5500 Tahoe Pines Rd.', 'Bakersfield', 'CA', '93312', 'Monthly');
INSERT INTO properties VALUES (6, 'RESIDENTIAL', '11778 TrackSide Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (7, 'RESIDENTIAL', '10216 Arapaho Ave.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (8, 'RESIDENTIAL', '11599 Reagan Rd.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (9, 'RESIDENTIAL', '13300 Boyd Lake Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (10, 'RESIDENTIAL', '5602 Danbury Ct.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (11, 'RESIDENTIAL', '12203 Portebello Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (12, 'RESIDENTIAL', '11059 Eagle Rock Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (13, 'RESIDENTIAL', '10844 4 Bears Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (14, 'RESIDENTIAL', '10499 Holland St.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (15, 'American Kids Sports Center', '3622 Allen Rd.', 'Bakersfield', 'CA', '93314', 'Monthly');
INSERT INTO properties VALUES (16, 'RESIDENTIAL', '15801 Tallus Ranch Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (17, 'RESIDENTIAL', '11801 River Run Blvd.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (18, 'Derrels Mini Storage', '13952 Rosedale Hwy.', 'Bakersfield', 'CA', '93312', 'Monthly');
INSERT INTO properties VALUES (19, 'Affordable RV Storage', '3858 Allen Rd.', 'Bakersfield', 'CA', '93314', 'Bi-Monthly');
INSERT INTO properties VALUES (20, 'RESIDENTIAL', '8715 Shoreview Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (21, 'RESIDENTIAL', '8600 Mainsail Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (22, 'RESIDENTIAL', '9002 Bienvenu Ct.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (23, 'RESIDENTIAL', '7700 Live Oak Way', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (24, 'RESIDENTIAL', '7799 Pembroke Ave.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (25, 'RESIDENTIAL', '8166 Norris Rd.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (26, 'RESIDENTIAL', '10157 Revere Beach Dr.', 'Bakersfield', 'CA', '93314', 'Bi-Monthly');
INSERT INTO properties VALUES (27, 'RESIDENTIAL', '10302 Stoneham St.', 'Bakersfield', 'CA', '93314', 'Bi-Monthly');
INSERT INTO properties VALUES (28, 'RESIDENTIAL', '19461 Stallion Way', 'Bakersfield', 'CA', '93314', 'Bi-Monthly');
INSERT INTO properties VALUES (29, 'RESIDENTIAL', '9313 Chinook Ave.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (30, 'RESIDENTIAL', '10800 Baron Ave.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (31, 'RESIDENTIAL', 'Twin Falls Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (32, 'RESIDENTIAL', '9500 Ravenrock Dr.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (33, 'RESIDENTIAL', '13841 Rowland Ave.', 'Bakersfield', 'CA', '93312', 'Bi-Monthly');
INSERT INTO properties VALUES (34, 'RESIDENTIAL', '10701 Hight Plateau Way', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (35, 'RESIDENTIAL', '11100 Laramie Peak Dr.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (36, 'RESIDENTIAL', '10233 Onyx Peak Ln.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (37, 'RESIDENTIAL', '10802 Villa Monterey Dr.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (38, 'RESIDENTIAL', '11100 Rancho Cordova St.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (39, 'RESIDENTIAL', '11400 Eresma Dr.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (40, 'RESIDENTIAL', '11400 Sangrado Dr.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (41, 'RESIDENTIAL', '9500 Godiva Ave.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (42, 'RESIDENTIAL', '9299 Campus Park Rd.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (43, 'RESIDENTIAL', '11200 Soltierra Pl.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (44, 'RESIDENTIAL', '9500 Eagle Oak Rd.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (45, 'RESIDENTIAL', '11700 Goodhue St.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (46, 'RESIDENTIAL', '3401 Via Rosa', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (47, 'RESIDENTIAL', '10499 Sunset Canyon Dr.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (48, 'Derrels Mini Storage', '9801 White Lane', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (49, 'The Broken Yolk Cafe', '3300 Buena Vista Rd.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (50, 'Aera Entergy LLC', '10000 Ming Ave.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (51, 'Cambridge Village Apartments', '8200 Laurelglen Blvd.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (52, 'RESIDENTIAL', 'Briarwood Ln.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (53, 'RESIDENTIAL', '5100 Sea Star Ln.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (54, 'RESIDENTIAL', '9402 Sumatra Ave.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (55, 'RESIDENTIAL', '2730 Mcnutt St.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (56, 'RESIDENTIAL', '8700 Swigert Ct.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (57, 'RESIDENTIAL', '8904 Summer Dream Ct.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (58, 'RESIDENTIAL', '9788 Lacroix Ct.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (59, 'RESIDENTIAL', '9700 Lightner Way', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (60, 'RESIDENTIAL', '10721 Desert View Pl.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (61, 'RESIDENTIAL', '4208 Windy Walk Ct.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (62, 'RESIDENTIAL', '11505 Heliotrope Court', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (63, 'RESIDENTIAL', '10803 Chadwick Ln.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (64, 'Cruz Thru Car Wash', '3300 Buena Vista Rd.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (65, 'RESIDENTIAL', '10483 Claridge Ct.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (66, 'RESIDENTIAL', '2598 Georgia Oak Dr.', 'Bakersfield', 'CA', '93311', 'Bi-Monthly');
INSERT INTO properties VALUES (67, 'RESIDENTIAL', '3198 Pomona St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (68, 'RESIDENTIAL', '3202 Annapolis Dr.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (69, 'RESIDENTIAL', '2798 Hawthorne Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (70, 'RESIDENTIAL', '300 Water St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (71, 'RESIDENTIAL', '798 Goodman St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (72, 'RESIDENTIAL', '398 Knotts St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (73, 'RESIDENTIAL', '125 La Mesa Dr.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (74, 'RESIDENTIAL', '2901 Elmwood Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (75, 'RESIDENTIAL', '2801 Rio Linda Dr.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (76, 'RESIDENTIAL', '1098 Shattuck Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (77, 'RESIDENTIAL', '2898 Cornell St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (78, 'RESIDENTIAL', '998 Pearl St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (79, 'RESIDENTIAL', '85 Flower St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (80, 'RESIDENTIAL', '598 Jeffery St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (81, 'RESIDENTIAL', '3501 Century Dr.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (82, 'RESIDENTIAL', '3198 Berger St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (83, 'RESIDENTIAL', '1000 Yale Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (84, 'RESIDENTIAL', '699 Skyline Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (85, 'RESIDENTIAL', '3698 Purdue Dr.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (86, 'RESIDENTIAL', '3498 Blade Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (87, 'RESIDENTIAL', '2998 Driller Ave.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (88, 'RESIDENTIAL', '501 Irene St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (89, 'RESIDENTIAL', '1431 Lincoln St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (90, 'RESIDENTIAL', '2508 Corto St.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (91, 'RESIDENTIAL', '1298 Tulare St.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (92, 'RESIDENTIAL', '2798 Kaibab Ave.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (93, 'RESIDENTIAL', '2500 Chrismas Tree Ln.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (94, 'RESIDENTIAL', '3610 Cardinal Ave.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (95, 'RESIDENTIAL', '3800 Pinehurst Dr.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (96, 'RESIDENTIAL', '1801 Kent Dr.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (97, 'RESIDENTIAL', '5707 Kingsland Ave.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (98, 'RESIDENTIAL', '5109 Pioneer Dr.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');
INSERT INTO properties VALUES (99, 'RESIDENTIAL', '3401 Filmore Ave.', 'Bakersfield', 'CA', '93305', 'Bi-Monthly');
INSERT INTO properties VALUES (100, 'RESIDENTIAL', '2701 Scott Pl.', 'Bakersfield', 'CA', '93306', 'Bi-Monthly');